Create Movie model
Leearning/pelis pull request #4
Opened 2022-07-31 02:13 UTC by cjsaez

2022-07-31 09:07 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/models/Movie.kt
> +    val original_title: String,
Isn't the naming convention in Kotling camel case? (`originalTitle` instead of `original_title`)

2022-07-31 18:57 UTC, cjsaez commented on app/src/main/java/com/example/pelis/models/Movie.kt
> +    val original_title: String,
Yes, I did putted those names because I was thinking in a library that I was going to use, then I remembered that I was not start with third party libraries.

2022-08-01 01:26 UTC, rlaguilar requested changes
This PR is named _Create Movie model_, but you also included the `PageResult`, `Records` and `Result` types. You can either change the title of the PR so that it actually reflects what you are doing, or you can only include the files corresponding to the title. Both approaches are fine.

2022-08-01 01:42 UTC, cjsaez commented
> This PR is named _Create Movie model_, but you also included the `PageResult`, `Records` and `Result` types. You can either change the title of the PR so that it actually reflects what you are doing, or you can only include the files corresponding to the title. Both approaches are fine.

2022-08-01 01:48 UTC, cjsaez commented
I did putted the correct name to this PR, but when I submit mare commits, they automatically was adding to this PR. That was not my intention.

2022-08-01 01:52 UTC, rlaguilar commented
> I did putted the correct name to this PR, but when I submit mare commits, they automatically was adding to this PR. That was not my intention.

Ok, try to fix it then.

2022-08-01 02:51 UTC, closed without merging