Create movie model and requested response wrappers
Leearning/pelis pull request #5
Opened 2022-08-01 03:03 UTC by cjsaez

2022-08-01 03:10 UTC, rlaguilar requested changes

2022-08-01 03:10 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/Records.kt
> +    val total_results: Int
Same as before with the naming convection. Try to keep an eye for the things I already corrected so I don't have to repeat myself :-)

2022-08-01 03:10 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/Result.kt
> +sealed class Result<out T : Any> {
Why are you using a custom Result type instead of using the Result type already included in the Kotlin standard library?

2022-08-01 03:10 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/PageResult.kt
> +sealed class PageResult<out T : Any> {
Why do you need an extra Page result instead of using the Result of Page?

2022-08-01 03:53 UTC, cjsaez commented on app/src/main/java/com/example/pelis/utils/Result.kt
> +sealed class Result<out T : Any> {
Because in standard library there is not the definition of Succes and Error classes. For me is better to use these sub-classes instead a property in order to know if the response was succesful or not; they make the code more understandable, readable and clear. The kotlin.Result class cannot be inherited.

2022-08-01 03:55 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/Result.kt
> +sealed class Result<out T : Any> {
Could you please show an example where you use your custom Result type and the Result type from the standard library, to clearly see the advantages you are talking about?

2022-08-01 03:55 UTC, cjsaez commented on app/src/main/java/com/example/pelis/utils/PageResult.kt
> +sealed class PageResult<out T : Any> {
Because in the case of items collections requests, we want to know if there is a next page of elements.

2022-08-03 15:22 UTC, cjsaez commented
You wasn't see my changes?

2022-08-04 00:11 UTC, rlaguilar approved these changes

2022-08-04 00:38 UTC, merged