Movies Service
Leearning/pelis pull request #6
Opened 2022-08-04 23:18 UTC by cjsaez

2022-08-05 04:00 UTC, rlaguilar requested changes

2022-08-05 04:00 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/application/PelisApp.kt
> +class PelisApp : Application() {
How is this related to the rest of the code?

2022-08-05 04:00 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/ApiRestMoviesDataSource.kt
> +interface ApiRestMoviesDataSource {
Having the `ApiRest` prefix isn't adequate for the interface. The name of the interface should indicate what it is for, not how it's implemented. In this case I think `MoviesDataSource` would work fine, and then the class that implements it using the rest API could be called `ApiRestMoviesDataSource`. Does that make sense?

2022-08-05 04:00 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/httpImpl/MoviesServiceImpl.kt
> +    override suspend fun getPopularMovies(page: Int): Result<Page<Movie>> {
There are a lot of things going on inside this function. In the talk I sent you the other day, they discuss how to do this part in a more decoupled way that will help a lot when it comes to testing this services.

2022-08-05 04:00 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/httpImpl/MoviesServiceImpl.kt
> +    }
If these functions aren't implemented yet, there is no need to define them in the interface. Add the functions to the interface when you are ready to implement them.

2022-08-05 04:00 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/Network.kt
> +open class Network {
This name is quite vague, try to find one that better describes the propose of the object.

2022-08-05 04:00 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/Network.kt
> +        var httpUrl = "$url?api_key=c475cd10dc10bac95e5884e5037eb359"
For security reasons, you should NEVER commit secret values to the repo. Implement this using Github secrets.

2022-08-05 14:09 UTC, cjsaez commented on app/src/main/java/com/example/pelis/application/PelisApp.kt
> +class PelisApp : Application() {
There are certain things in android project for which it is necessary to create the app class. One of these is the dependencies injection. All project uses Hilt as dependencies injection library must to annotate the app class.

2022-08-05 14:26 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/application/PelisApp.kt
> +class PelisApp : Application() {
Do you remember we talked about not using any library for managing dependency injection?

2022-08-05 19:26 UTC, cjsaez commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/ApiRestMoviesDataSource.kt
> +interface ApiRestMoviesDataSource {
Make sense, but, if I have others data source, for example, aws appsync backend, and some information comes to one source and some from the other one I would need two abstraction of both. I am not abstracting the different sources, I am abstracting the implementation of each source. For example, if that data comes from api rest, I culd giving it an implementation using retrofilt, volley or native way (this case); for database source I could do it using room or objectBox, etc. Maybe I am not right at all, you tell me.

2022-08-05 20:18 UTC, cjsaez commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/httpImpl/MoviesServiceImpl.kt
> +    override suspend fun getPopularMovies(page: Int): Result<Page<Movie>> {
Ok, the class Network (I will to change its name) provides that decoupled way, but always has to be a block of code that join that decoupled functionalities; in this case was "getPopularMovies", in the talk was some function.

2022-08-06 00:48 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/ApiRestMoviesDataSource.kt
> +interface ApiRestMoviesDataSource {
> if I have others data source

 You don't have any other data source. You don't write code to handle all possible scenarios, but the scenarios you have and the ones that are very likely to occur.

2022-08-06 01:05 UTC, rlaguilar requested changes
Re-request a review after you've addressed the comments in the PR, and it's ready for me to review it again. Answering my comments doesn't need to re-request a review.

2022-08-06 01:05 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/httpImpl/MoviesServiceImpl.kt
> +    override suspend fun getPopularMovies(page: Int): Result<Page<Movie>> {
Have a look at [this project](https://github.com/rlaguilar/swifty-net) I'm working on. Basically it's modelling the network service layer, same thing you're trying to do in this PR. The source files are at `Sources/SwiftyNet/` and the tests are at `Tests/SwiftyNetTests/`. In particular, try to understand how the following types work together:
- `NetworkChannel`
- `Request`
- `URLRequestBuilder`

Notice how the `NetworkChannel` type is the one that put all pieces together, it doesn't have any logic inside it.

2022-08-06 23:00 UTC, cjsaez commented on app/src/main/java/com/example/pelis/application/PelisApp.kt
> +class PelisApp : Application() {
I forgot that I shouldn't use third party library for dependencies injection either.

2022-08-06 23:03 UTC, cjsaez commented on app/src/main/java/com/example/pelis/utils/Network.kt
> +        var httpUrl = "$url?api_key=c475cd10dc10bac95e5884e5037eb359"
In order to do that I need access to the secrets of the GitHub repository

2022-08-06 23:07 UTC, rlaguilar commented
Again:
> Re-request a review after you've addressed the comments in the PR, and it's ready for me to review it again. Answering my comments doesn't need to re-request a review.

It's the third time I need to tell you this. Is there any reason why it isn't clear enough? Should I say it in a different way?

2022-08-06 23:54 UTC, rlaguilar requested changes

2022-08-06 23:54 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/httpImpl/MoviesServiceImpl.kt
> +class MoviesServiceImpl (baseUrl: String) : MoviesDataSource,
Shouldn't the name be `MoviesDataSourceImpl`?

2022-08-06 23:54 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/dataSources/movies/remote/httpImpl/MoviesServiceImpl.kt
> +        requestFactory = object : MoviesRequestFactory() {
Why do you need `MoviesRequestFactory` to be abstract instead of having its own logic? If you implement the logic of `getPopularMoviesRequest` inside `MoviesServiceImpl`, the request building logic is still the responsibility of `MoviesServiceImpl`.

2022-08-06 23:54 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/NetworkRequestOperations.kt
> +                            else URL(httpUrl).openConnection() as HttpURLConnection
Why can't you just do `val urlConnection = URL(httpUrl).openConnection() as HttpURLConnection`?

2022-08-06 23:54 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/NetworkRequestOperations.kt
> +            200 -> Result.success(response.body)
You don't need to change this now because we are probably move away from this implementation, but the success status codes are all in the range [200, 299], it isn't only 200.

2022-08-06 23:54 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/NetworkRequestOperations.kt
> +    enum class RequestType {
This enum contains the different http methods, so a more appropriate name for this type should be `RequestMethod`.

2022-08-07 00:48 UTC, cjsaez commented on app/src/main/java/com/example/pelis/utils/NetworkRequestOperations.kt
> +                            else URL(httpUrl).openConnection() as HttpURLConnection
I have a concept error here.

2022-08-07 00:59 UTC, cjsaez commented on app/src/main/java/com/example/pelis/utils/NetworkRequestOperations.kt
> +            200 -> Result.success(response.body)
I research all status codes possible in movies backend and for success request it only use 200. I think that whatever the implementation is maybe I will need to have a function like this in order to take a decision depending on the status code. Am I right?

2022-08-07 09:13 UTC, rlaguilar commented on app/src/main/java/com/example/pelis/utils/NetworkRequestOperations.kt
> +                var inputLine = reader.readLine()
At which point is the network request sent to the server? I see that in line 21 you are still configuring the request and in line 26 you're already consuming it. Where are you triggering the request?

2022-08-07 17:06 UTC, cjsaez commented on app/src/main/java/com/example/pelis/utils/NetworkRequestOperations.kt
> +                var inputLine = reader.readLine()
The method url.openConnection create the connection to the server but not stablish it, the request will be executed when getResponseCode(), connect(), getInputStream() or getOutputStream() methods will be called.

2022-08-07 21:51 UTC, rlaguilar approved these changes
There are still a couple of things that should be changed but we are gonna leave those for a follow up PR.

2022-08-08 00:42 UTC, merged